version: 1

reviews:
  profile: chill            # or: assertive, balanced
  auto_review:
    enabled: true
    on:
      - pull_request_opened
      - pull_request_synchronize
  path_filters:
    - "!node_modules/**"
    - "!public/**"
    - "!**/*.svg"
    - "!**/*.md"
  tools:
    tests:
      enabled: true
    complexity:
      enabled: true
    security:
      enabled: true
    performance:
      enabled: true
    style:
      enabled: true

comments:
  review_threads: true
  summary: true
  max_comments: 40

general:
  language: en
  respect_existing_comments: true